import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../screens/my_home_screen.dart';
import 'api_model.dart';
import 'package:http/http.dart' as http;

Future<Autogenerated> apiLoginPhone(
  String phoneNumber,
  BuildContext context,
) async {
  var request = http.MultipartRequest(
      'POST', Uri.parse('http://50.17.68.62/crwd/api/login_with_phone'));
  request.fields.addAll({
    'phone_number': phoneNumber,
    'device_type': 'Android',
    'device_token': '1',
    'referral_code': 'run',
  });

  http.StreamedResponse response = await request.send();
  var jsonResponse = jsonDecode(await response.stream.bytesToString());
  return Autogenerated.fromJson(jsonResponse);
}

Future<Autogenerated?> apiLoginGoogle(
    BuildContext context,
  String socialId,
) async {
  String username = 'crwd';
  String password = 'Q1JXRCBjcmVhdGVkIGJ5IGNoYW5kYW4';
  String basicAuth =
      'Basic ' + base64Encode(utf8.encode('$username:$password'));
  var jsonResponse = null;
  var response = await http.post(
    Uri.parse('http://50.17.68.62/crwd/api/social_login'),

headers: {'authorization': basicAuth},
    body: { 'social_id': '112373434782800182798',
      'name': 'Quality Analyst',
      'email': 'analystq16@gmail.com',
      'device_type': 'Android',
      'device_token': '1',
      'social_type': 'Google',
      'referral_code': 'run',},


  );


  print(response.body);
  jsonResponse = json.decode(response.body);
  var message = jsonResponse["message"];

  if (response.statusCode == 200) {
    print("Get all notification api success");
    Navigator.of(context).push(
        MaterialPageRoute(builder: (BuildContext context) => const MyHome()));
    return Autogenerated.fromJson(jsonResponse);
  } else if (response.statusCode == 401) {

  } else {

    throw Exception("Failed to load the work experience!");
  }
  // var request = http.MultipartRequest(
  //     'POST', Uri.parse('http://50.17.68.62/crwd/api/social_login')
  //     ,
  // );
  //
  // request.fields.addAll({
  //
  // });
  //
  // http.StreamedResponse response = await request.send();
  // var jsonResponse = jsonDecode(await response.stream.bytesToString());
  // return Autogenerated.fromJson(jsonResponse);
}
